In [1]:
#testing codespace
print("hello")

hello


In [3]:
#import the tensorflow library
import tensorflow as tf

In [4]:
#tensor data types and creation
string = tf.Variable("this is a string", tf.string) #string data type
number = tf.Variable(324, tf.int16) #int16(2 bytes) data type
floating =tf.Variable(4.56,tf.float64) #float64(8 bytes) data type


In [6]:
#rank/dimension of a tensor
r0=tf.Variable("hello",tf.string) #rank 0 tensor(scalar)
r1=tf.Variable(["hello","world"],tf.string) #rank 1 tensor(vector)
r2=tf.Variable([["hello","world"],["hello","world"]],tf.string) #rank 2 tensor(matrix)

In [9]:
#check the rank of the tensor
#the numpy defines the rank of the tensor
tf.rank(r1)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [13]:
#shape of the tensor
r1.shape

TensorShape([2])

In [14]:
#multiranked tensor
t1=tf.Variable([[[1,1,1],[1,1,1]]])
t1.shape

TensorShape([1, 2, 3])

In [16]:
#reshaping a tensor
t2=tf.reshape(t1,[3,2,1])
print(t2)

tf.Tensor(
[[[1]
  [1]]

 [[1]
  [1]]

 [[1]
  [1]]], shape=(3, 2, 1), dtype=int32)
